//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cikolataEntities : DbContext
    {
        public cikolataEntities()
            : base("name=cikolataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblFavori> tblFavori { get; set; }
        public virtual DbSet<tblFiyat> tblFiyat { get; set; }
        public virtual DbSet<tblKategori> tblKategori { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblKullaniciRol> tblKullaniciRol { get; set; }
        public virtual DbSet<tblMesaj> tblMesaj { get; set; }
        public virtual DbSet<tblPromOnay> tblPromOnay { get; set; }
        public virtual DbSet<tblPromosyon> tblPromosyon { get; set; }
        public virtual DbSet<tblSepet> tblSepet { get; set; }
        public virtual DbSet<tblSepetDty> tblSepetDty { get; set; }
        public virtual DbSet<tblSiparisDetay> tblSiparisDetay { get; set; }
        public virtual DbSet<tblStok> tblStok { get; set; }
        public virtual DbSet<tblUrun> tblUrun { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_toplamSatilanUrun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_toplamSatilanUrun");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_toplamUyeSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_toplamUyeSayisi");
        }
    
        public virtual ObjectResult<sp_encoksatbesurun_Result> sp_encoksatbesurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_encoksatbesurun_Result>("sp_encoksatbesurun");
        }
    
        public virtual ObjectResult<sp_encoksatisyapilankategori_Result> sp_encoksatisyapilankategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_encoksatisyapilankategori_Result>("sp_encoksatisyapilankategori");
        }
    
        public virtual ObjectResult<sp_encoksepeteurunlerilkbes_Result> sp_encoksepeteurunlerilkbes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_encoksepeteurunlerilkbes_Result>("sp_encoksepeteurunlerilkbes");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gunluksatilanurunsayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gunluksatilanurunsayisi");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_gunlukuyekayitsayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_gunlukuyekayitsayisi");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_haftaliksatilanurunsayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_haftaliksatilanurunsayisi");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_haftalikuyekayitsayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_haftalikuyekayitsayisi");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_tumsatilanurunsayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_tumsatilanurunsayisi");
        }
    }
}
