//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFavori
    {
        public int favoriID { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<bool> favoriDurumu { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblUrun tblUrun { get; set; }
    }
}
