//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFiyat()
        {
            this.tblUrun = new HashSet<tblUrun>();
        }
    
        public int fiyatID { get; set; }
        public Nullable<int> urunPromosyonID { get; set; }
        public double alisFiyati { get; set; }
        public double satisFiyati { get; set; }
    
        public virtual tblPromosyon tblPromosyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrun> tblUrun { get; set; }
    }
}
