//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblFavori = new HashSet<tblFavori>();
            this.tblMesaj = new HashSet<tblMesaj>();
            this.tblPromOnay = new HashSet<tblPromOnay>();
            this.tblSepet = new HashSet<tblSepet>();
            this.tblUrun = new HashSet<tblUrun>();
        }
    
        public int kullaniciID { get; set; }
        public Nullable<int> kullaniciRolID { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullanciSoyad { get; set; }
        public string kullaniciSifre { get; set; }
        public System.DateTime kullaniciKayitTarihi { get; set; }
        public string mail { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavori> tblFavori { get; set; }
        public virtual tblKullaniciRol tblKullaniciRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaj> tblMesaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPromOnay> tblPromOnay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSepet> tblSepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrun> tblUrun { get; set; }
        public virtual tblKullanici tblKullanici1 { get; set; }
        public virtual tblKullanici tblKullanici2 { get; set; }
    }
}
