//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromOnay
    {
        public int onayID { get; set; }
        public int PromosyonId { get; set; }
        public int saticiId { get; set; }
        public int urunID { get; set; }
        public Nullable<bool> onayDurumu { get; set; }
        public Nullable<double> satisFiyat { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblPromosyon tblPromosyon { get; set; }
        public virtual tblUrun tblUrun { get; set; }
    }
}
