//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CikolataWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSepetDty
    {
        public int sepetDtyID { get; set; }
        public Nullable<int> sepetID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<byte> urunAdet { get; set; }
        public double topFiyat { get; set; }
        public Nullable<System.DateTime> eklenmeTarihi { get; set; }
        public Nullable<bool> sepetDurum { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual tblSepet tblSepet { get; set; }
        public virtual tblUrun tblUrun { get; set; }
    }
}
